# Generated by Django 4.0.4 on 2022-04-28 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('date', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
