# Generated by Django 4.0.4 on 2022-04-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('date', '0002_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productslist',
            name='expiry_date',
            field=models.DateField(verbose_name='expiry date'),
        ),
    ]
