# Generated by Django 4.0.4 on 2022-04-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('date', '0003_alter_productslist_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productslist',
            name='expiry_date',
            field=models.DateField(),
        ),
    ]
